[2023-09-18T10:58:39.409] [ERROR] application - UnauthorizedError: Authentication Error
    at Object.throw (E:\demo\vscode\nodePsql\node_modules\koa\lib\context.js:97:11)
    at jwt (E:\demo\vscode\nodePsql\node_modules\koa-jwt\lib\index.js:23:22)
    at E:\demo\vscode\nodePsql\node_modules\koa-unless\index.js:29:12
    at dispatch (E:\demo\vscode\nodePsql\node_modules\koa-compose\index.js:42:32)
    at E:\demo\vscode\nodePsql\node_modules\@koa\router\lib\router.js:425:16
    at dispatch (E:\demo\vscode\nodePsql\node_modules\koa-compose\index.js:42:32)
    at E:\demo\vscode\nodePsql\node_modules\koa-compose\index.js:34:12
    at dispatch (E:\demo\vscode\nodePsql\node_modules\@koa\router\lib\router.js:430:31)
    at dispatch (E:\demo\vscode\nodePsql\node_modules\koa-compose\index.js:42:32)
    at cors (E:\demo\vscode\nodePsql\node_modules\@koa\cors\index.js:108:22) {
  headers: {
    'Access-Control-Allow-Origin': 'http://localhost:8000',
    'Access-Control-Allow-Credentials': 'true',
    vary: 'Origin'
  }
}
[2023-09-18T10:58:51.878] [ERROR] application - UnauthorizedError: Authentication Error
    at Object.throw (E:\demo\vscode\nodePsql\node_modules\koa\lib\context.js:97:11)
    at jwt (E:\demo\vscode\nodePsql\node_modules\koa-jwt\lib\index.js:23:22)
    at E:\demo\vscode\nodePsql\node_modules\koa-unless\index.js:29:12
    at dispatch (E:\demo\vscode\nodePsql\node_modules\koa-compose\index.js:42:32)
    at E:\demo\vscode\nodePsql\node_modules\@koa\router\lib\router.js:425:16
    at dispatch (E:\demo\vscode\nodePsql\node_modules\koa-compose\index.js:42:32)
    at E:\demo\vscode\nodePsql\node_modules\koa-compose\index.js:34:12
    at dispatch (E:\demo\vscode\nodePsql\node_modules\@koa\router\lib\router.js:430:31)
    at dispatch (E:\demo\vscode\nodePsql\node_modules\koa-compose\index.js:42:32)
    at cors (E:\demo\vscode\nodePsql\node_modules\@koa\cors\index.js:108:22) {
  headers: {
    'Access-Control-Allow-Origin': 'http://localhost:8000',
    'Access-Control-Allow-Credentials': 'true',
    vary: 'Origin'
  }
}
[2023-09-18T10:58:55.106] [ERROR] application - UnauthorizedError: Authentication Error
    at Object.throw (E:\demo\vscode\nodePsql\node_modules\koa\lib\context.js:97:11)
    at jwt (E:\demo\vscode\nodePsql\node_modules\koa-jwt\lib\index.js:23:22)
    at E:\demo\vscode\nodePsql\node_modules\koa-unless\index.js:29:12
    at dispatch (E:\demo\vscode\nodePsql\node_modules\koa-compose\index.js:42:32)
    at E:\demo\vscode\nodePsql\node_modules\@koa\router\lib\router.js:425:16
    at dispatch (E:\demo\vscode\nodePsql\node_modules\koa-compose\index.js:42:32)
    at E:\demo\vscode\nodePsql\node_modules\koa-compose\index.js:34:12
    at dispatch (E:\demo\vscode\nodePsql\node_modules\@koa\router\lib\router.js:430:31)
    at dispatch (E:\demo\vscode\nodePsql\node_modules\koa-compose\index.js:42:32)
    at cors (E:\demo\vscode\nodePsql\node_modules\@koa\cors\index.js:108:22) {
  headers: {
    'Access-Control-Allow-Origin': 'http://localhost:8000',
    'Access-Control-Allow-Credentials': 'true',
    vary: 'Origin'
  }
}
[2023-09-18T11:57:55.018] [ERROR] application - UnauthorizedError: Authentication Error
    at Object.throw (E:\demo\vscode\nodePsql\node_modules\koa\lib\context.js:97:11)
    at jwt (E:\demo\vscode\nodePsql\node_modules\koa-jwt\lib\index.js:23:22)
    at E:\demo\vscode\nodePsql\node_modules\koa-unless\index.js:29:12
    at dispatch (E:\demo\vscode\nodePsql\node_modules\koa-compose\index.js:42:32)
    at E:\demo\vscode\nodePsql\node_modules\@koa\router\lib\router.js:425:16
    at dispatch (E:\demo\vscode\nodePsql\node_modules\koa-compose\index.js:42:32)
    at E:\demo\vscode\nodePsql\node_modules\koa-compose\index.js:34:12
    at dispatch (E:\demo\vscode\nodePsql\node_modules\@koa\router\lib\router.js:430:31)
    at dispatch (E:\demo\vscode\nodePsql\node_modules\koa-compose\index.js:42:32)
    at cors (E:\demo\vscode\nodePsql\node_modules\@koa\cors\index.js:108:22) {
  headers: {
    'Access-Control-Allow-Origin': 'http://localhost:8000',
    'Access-Control-Allow-Credentials': 'true',
    vary: 'Origin'
  }
}
[2023-09-18T18:27:04.133] [ERROR] application - UnauthorizedError: Authentication Error
    at Object.throw (E:\demo\vscode\nodePsql\node_modules\koa\lib\context.js:97:11)
    at jwt (E:\demo\vscode\nodePsql\node_modules\koa-jwt\lib\index.js:23:22)
    at E:\demo\vscode\nodePsql\node_modules\koa-unless\index.js:29:12
    at dispatch (E:\demo\vscode\nodePsql\node_modules\koa-compose\index.js:42:32)
    at E:\demo\vscode\nodePsql\node_modules\@koa\router\lib\router.js:425:16
    at dispatch (E:\demo\vscode\nodePsql\node_modules\koa-compose\index.js:42:32)
    at E:\demo\vscode\nodePsql\node_modules\koa-compose\index.js:34:12
    at dispatch (E:\demo\vscode\nodePsql\node_modules\@koa\router\lib\router.js:430:31)
    at dispatch (E:\demo\vscode\nodePsql\node_modules\koa-compose\index.js:42:32)
    at cors (E:\demo\vscode\nodePsql\node_modules\@koa\cors\index.js:108:22) {
  headers: {
    'Access-Control-Allow-Origin': 'http://localhost:8000',
    'Access-Control-Allow-Credentials': 'true',
    vary: 'Origin'
  }
}
[2023-09-18T18:27:12.677] [ERROR] application - UnauthorizedError: Authentication Error
    at Object.throw (E:\demo\vscode\nodePsql\node_modules\koa\lib\context.js:97:11)
    at jwt (E:\demo\vscode\nodePsql\node_modules\koa-jwt\lib\index.js:23:22)
    at E:\demo\vscode\nodePsql\node_modules\koa-unless\index.js:29:12
    at dispatch (E:\demo\vscode\nodePsql\node_modules\koa-compose\index.js:42:32)
    at E:\demo\vscode\nodePsql\node_modules\@koa\router\lib\router.js:425:16
    at dispatch (E:\demo\vscode\nodePsql\node_modules\koa-compose\index.js:42:32)
    at E:\demo\vscode\nodePsql\node_modules\koa-compose\index.js:34:12
    at dispatch (E:\demo\vscode\nodePsql\node_modules\@koa\router\lib\router.js:430:31)
    at dispatch (E:\demo\vscode\nodePsql\node_modules\koa-compose\index.js:42:32)
    at cors (E:\demo\vscode\nodePsql\node_modules\@koa\cors\index.js:108:22) {
  headers: {
    'Access-Control-Allow-Origin': 'http://localhost:8000',
    'Access-Control-Allow-Credentials': 'true',
    vary: 'Origin'
  }
}
[2023-09-18T18:42:23.895] [ERROR] application - UnauthorizedError: Authentication Error
    at Object.throw (E:\demo\vscode\nodePsql\node_modules\koa\lib\context.js:97:11)
    at jwt (E:\demo\vscode\nodePsql\node_modules\koa-jwt\lib\index.js:23:22)
    at E:\demo\vscode\nodePsql\node_modules\koa-unless\index.js:29:12
    at dispatch (E:\demo\vscode\nodePsql\node_modules\koa-compose\index.js:42:32)
    at E:\demo\vscode\nodePsql\node_modules\@koa\router\lib\router.js:425:16
    at dispatch (E:\demo\vscode\nodePsql\node_modules\koa-compose\index.js:42:32)
    at E:\demo\vscode\nodePsql\node_modules\koa-compose\index.js:34:12
    at dispatch (E:\demo\vscode\nodePsql\node_modules\@koa\router\lib\router.js:430:31)
    at dispatch (E:\demo\vscode\nodePsql\node_modules\koa-compose\index.js:42:32)
    at cors (E:\demo\vscode\nodePsql\node_modules\@koa\cors\index.js:108:22) {
  headers: {
    'Access-Control-Allow-Origin': 'http://localhost:8000',
    'Access-Control-Allow-Credentials': 'true',
    vary: 'Origin'
  }
}
